---
name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install deps
        run: |
          uv sync

      - name: ruff check
        run: uv run ruff check --no-cache

      - name: ruff format
        run: uv run ruff format --check --no-cache

      - name: mypy
        run: uv run mypy .

      - name: tests
        run: uv run pytest
